# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir -p ~/.ssh
          - echo "159.203.136.184 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd+P84r8j22sU4LwohqrcN6AGKYxeLNgOOWD/S8Wnjw20nACBQnYpgImHzeQfFAFNtlM3sZeRDpEduePMHpdo9NtPRo/fI0BaC2KoDjBG2HGX6lV0bEEk8u36lpALrFaIgdIuqEiVNDXLnLFIWi06fjYwlc86hX0UBGqLciLp+jxARfzxO6e5RI+lptuJcjFiEaP55CcdAtYgi9SqcKUnwnx7aDYI74MjL39JI4Q5IcXYMvptAmo4TOwaBtC1d/vhC3ei3i/Mel8UMovD7gZufeHGXimgfh30B/gIcfG46SfdBTW+mkM9HYbW2kl6OZZ2D3dI6SDhQx9Z4DiUAlJi9" > ./test.txt
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode -i > ~/.ssh/id_rsa)
          - make 