# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir -p ~/.ssh
          - ehco "159.203.136.184 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGqghr9ZL6GXfHZ7BEv6E+zmbPIUujt1ZGUW/ugEupilC0/zkS6lN8jWzzIXVM95uGVGTLANekBEl0H0oSH3ti4=" > ~/.ssh/known_hosts
          - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - ssh root@159.203.136.184 'cd ~/portfolio-static/web && make deploy'