# name: CI
name: Build Production Docker Image

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Login to registry
      uses: actions/docker/login@master
      env: 
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: santi6291
        DOCKER_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
    - name: Install dependencies
      uses: docker://node:10.15.3
      with:
        entrypoint: npm
        args: install
    - name: Compile Frontend Assets
      uses: docker://node:10.15.3
      with:
        entrypoint: make
        args: build-prod
    - name: Build Docker Image
      uses: actions/docker/cli@7ffaaef
      with:
        args: build ./ --no-cache -t santisosa-portfolio-static 
    - name: Tag image
      uses: actions/docker/tag@04185cf
      with:
        args: santisosa-portfolio-static docker.pkg.github.com/santi6291/portfolio-static/santisosa-portfolio-static
    - name: Push Image
      uses: actions/docker/cli@7ffaaef
      with:
        args: push docker.pkg.github.com/santi6291/portfolio-static/santisosa-portfolio-static

