name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
      env:
          NODE_ENV: production
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: public
          path: public